version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: db_caching

    ports:
      - "3307:3306"